site_name: Awesome .Net Core Educations
site_url: https://mehdihadeli.github.io/awesome-dotnet-core-education/
site_description: A curated list of awesome articles and resources for learning and practicing about .Net Core and its related technologies.
docs_dir: docs/
repo_name: 'GitHub'
repo_url: https://github.com/mehdihadeli/awesome-dotnet-core-education
theme: 
  name: material 
  prev_next_buttons_location: both
  navigation_depth: 4
  titles_only: False
  sticky_navigation: True
extra_css:
  - static/extra.css
markdown_extensions:
  - smarty
  - sane_lists
  - fenced_code
  - meta
  - admonition
  - attr_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  #- pymdownx.emoji:
  #    emoji_index: !!python/name:pymdownx.emoji.twemoji
  #    emoji_generator: !!python/name:pymdownx.emoji.to_svg
  #- pymdownx.emoji:
  #    emoji_index: !!python/name:materialx.emoji.twemoji
  #    emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - codehilite
  - footnotes
  - toc:
      permalink: true
      #baselevel: 2
nav:
  - .Net:
    - .Net : dotnet/dotnet.md
    - .Net 5: dotnet/dotnet5.md
    - .Net 6: dotnet/dotnet6.md  
    - .Net Standard: dotnet/dotnet-standard.md
    - ASP.Net Core: dotnet/dotnet-core.md
  - .Net CLI: 
    - .Net CLI: dotnet-cli/dotnet-cli.md
    - .Net Template: dotnet-cli/dotnet-template.md
    - .Net Tools: dotnet/dotnet-tools.md
    - .Net Watch: dotnet/dotnet-watch.md
    - Upgrade Assistant: dotnet-cli/upgrade-assistant.md
  - .Net Core Tips: dotnet/dotnet-core-tips.md
  - .Net Async: dotnet/async/index.md
  - MetaPack: dotnet/metapack.md
  - C#: csharp/index.md
  - Code Coverage & Analysis: code-coverage-analysis.md
  - MAUI: maui.md
  - Blazor: blazor.md
  - API Documentation: api-documentation.md
  - Source Generators: source-generators.md
  - Performance: performance.md
  - Health Check: health-check.md
  - Serialization: serialization.md
  - Generic Host And Web Host: generic-host.md
  - .Net Core Architecture: dotnet-core-architecture.md
  - Hosting: hosting.md
  - Kestrel: kestrel.md
  - Feature Flags: feature-flags.md
  - REST: rest.md
  - Middleware: middleware.md
  - Action Filters: action-filters.md
  - Configuration: configuration.md
  - HttContext: httpcontext.md
  - Options Pattern: options-pattern.md
  - gRPC: grpc.md
  - WebSockets: web-sockets.md
  - SignalR: signalr.md
  - HttpClient: httpclient.md
  - WEB API: web-api.md
  - Minimal API: minimal-api.md
  - Background Tasks: background-tasks.md
  - Validation: validation.md
  - Razor Pages: razor-pages.md
  - GraphQL: graphql.md
  - NoSQL: 
    - NoSQL: nosql/nosql.md
    - CosmosDB: nosql/cosmosdb.md
    - PostgreSQL: nosql/postgrsql.md
    - MongoDB: nosql/mongodb.md
    - RavenDB: nosql/ravendb.md
  - Docker: docker.md
  - Git: git.md
  - Elastic Search: elastic-search.md
  - Nuget: nuget.md
  - API Versioning: api-versioning.md
  - Hosted Service: hosted-service.md
  - Routing: routing.md
  - Dependency Injection: dependency-injection.md
  - Security: 
    - Security: security/security.md
    - Encryption And Data Protection: security/encryption.md
    - .Net Core Identity: security/dotnet-identity.md
    - Identity Server: security/identity-server.md
    - MSAL: security/msal.md
    - Authentication: security/authentication.md
    - Authorization: security/authorization.md
    - OAuth & OpenID Connect: security/oauth-opencid.md
    - Refresh Token: security/refresh-token.md
    - Secret Management: security/secret-management.md
  - Logging And Auditing: logging.md
  - Tracing: tracing.md
  - Testing: 
    - Testing: testing/testing.md
    - Unit Testing: testing/unit-testing.md
    - Integration Testing: testing/integration-testing.md
    - End-To-End Testing: testing/end-to-end-testing.md
    - Acceptance Testing: testing/acceptance-testing.md
    - Load Testing: testing/load-testing.md
    - Architectural Testing: testing/architectural-testing.md
    - Contract Testing: testing/contract-testing.md
    - Test Host And WebApplicationFactory: testing/test-host.md
    - Mocking: testing/mocking.md
    - TDD: testing/tdd.md
    - BDD: testing/bdd.md
  - Exception Handling: exception-handling.md
  - EF Core: 
    - EF Core: ef-core/ef-core.md
    - EF Core 5: ef-core/ef-core-5.md
    - Expression Tree: ef-core/expression-tree.md
    - EF Core Migrations: ef-core/ef-core-migration.md
  - Environment: environment.md
  - Mediator: mediator.md
  - Mapping: mapping.md
  - Caching: caching.md
  - Benchmarking: benchmarking.md
  - Package Versioning: package-versioning.md
  - Orleans: orleans.md
  - CI/CD: 
    - Azure Devops: ci-cd/azure-devops.md
    - GitHub Actions: ci-cd/gitHub-actions.md
    - Jenkins: ci-cd/jenkins.md
  - PaaS:
    - Heroku: paas/heroku.md
    - Netlify: paas/netlify.md
  - Roslyn: roslyn.md
  - IDE & Tools: 
    - Reharper & Rider: ide-tools/resharper-rider.md
    - GitHub: ide-tools/github.md
    - Decompile: ide-tools/decompile.md
    - DotMemory: ide-tools/dotmemory.md
    - Terminal Tools: ide-tools/terminal.md
    - WSL: ide-tools/wsl.md
  - Commenting: commenting.md
  - Others: others.md


copyright: 2021 <a href="https://github.com/mehdihadeli">Mehdi Hadeli</a>.
#remote_branch: gh-pages 
#remote_name: origin
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mehdi_hadeli
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mehdihadeli
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mehdihadeli